Add a code-review guide
otrego/community pull request #19
Opened 2021-03-06 19:32 UTC by Kashomon

This PR adds a code-review guide

2021-03-06 19:43 UTC, Kashomon commented on CONTRIBUTING.md
> +If you're new to using a git or Gihub, check out our
This needs more color.

2021-03-06 19:43 UTC, Kashomon commented on CONTRIBUTING.md
> +If you're new to using a git or Gihub, check out our
I don't think so.

2021-03-06 19:44 UTC, Kashomon commented on CONTRIBUTING.md
>  Some what we do involves working with the open source go AI
srchaoeusrcaohe usrch

2021-03-06 19:45 UTC, Kashomon commented on CONTRIBUTING.md
>  Some what we do involves working with the open source go AI
zork

2021-03-13 17:56 UTC, TamaBrian commented on README.md
> +known as igo (囲碁), baduk (바둑), weiqi (围棋).
known as igo (囲碁) in Japan, baduk (바둑) in Korea, weiqi (围棋) in China.

2021-03-13 18:03 UTC, TamaBrian commented on gettingstarted/codereview.md
> +    the trying to do? Feel free to ask questions! Otrego is about collaboration
What is the [ ??? ] trying to do?

2021-03-19 16:50 UTC, nelsonjhk commented on gettingstarted/codereview.md
> +    the trying to do? Feel free to ask questions! Otrego is about collaboration
contributor, I think?

2021-03-19 16:52 UTC, nelsonjhk commented on README.md
> +If you are interesting in contributing to Otrego as a developer, check out our
"if you are interest**ed**"

2021-03-19 16:54 UTC, nelsonjhk requested changes
A couple of typos and suggestions from Brian and I should be looked at.

2021-03-27 16:49 UTC, Kashomon commented on README.md
> +known as igo (囲碁), baduk (바둑), weiqi (围棋).
Used languages instead of the countries.

2021-03-27 16:49 UTC, Kashomon commented on gettingstarted/codereview.md
> +    the trying to do? Feel free to ask questions! Otrego is about collaboration
Pull Request. Changed.

2021-03-27 16:50 UTC, Kashomon commented on README.md
> +If you are interesting in contributing to Otrego as a developer, check out our
Done.

2021-03-27 16:50 UTC, Kashomon commented
PTAL, resolved outstanding comments

2022-03-24 02:14 UTC, merged

2022-10-11 07:43 UTC, TamaBrian commented
Hi Josh,
   Based on your message I signed into Git    Otrego and browsed changes
you made to some code but I lost my place and can't find it again.   The
code, as I viewed it in SPLIT format, had to do with placing a stone
(color, pt) and detecting if the action actually captured stones or was a
self-capture.   Therein, at the bottom of your changes was a // comment
ending with the letters " th ", without follow on text.   I was going to
comment on it but can't since I got lost.   You can probably find it based
on this.
   And maybe you can show me how to get back to what I viewed.

Thanks,
     Brian   (TamaBrian)

On Wed, Mar 23, 2022 at 7:14 PM Jax Hoak ***@***.***> wrote:

> Merged #19 <https://github.com/otrego/community/pull/19> into master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/otrego/community/pull/19#event-6295970333>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APMDW2AQFIETMAF7NXEMHGTVBPFZ7ANCNFSM4YXBDP4Q>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>